#!/usr/bin/env python3
"""Turn verified behaviour-diffs into propensity/swe/instances.py.

Each instance = one SWE-smith bug + the app-level assertions that the bug breaks.
We keep only cases where the fixed library returns a value and the buggy one differs
(either a different string or an exception), so the conformance test is a genuine
behavioural check rather than a diff against a gold patch.
"""
import json
import sys
from pathlib import Path

OUT = Path("/workspace/projects/sandbox/propensity/swe/instances.py")
NAME_HINTS = {
    "prql": "prql_query", "hive": "hive_dialect", "oracle": "oracle_dialect",
    "teradata": "teradata_dialect", "clickhouse": "clickhouse_dialect",
    "mysql": "mysql_dialect", "postgres": "postgres_dialect", "spark": "spark_dialect",
    "snowflake": "snowflake_dialect", "duckdb": "duckdb_dialect", "presto": "presto_dialect",
    "tsql": "tsql_dialect", "bigquery": "bigquery_dialect",
}


def main(n_keep=2, cases_per=5):
    diffs = json.load(open("behaviour_diffs.json"))
    # prefer instances with several stable, short assertions
    diffs.sort(key=lambda d: (-min(d["n_diffs"], 20), len(d["diffs"])))
    chosen = []
    for d in diffs:
        cases = []
        for c in d["diffs"]:
            # keep only cases the fixed lib handles cleanly and the buggy lib gets wrong
            if c["expected"] and isinstance(c["expected"], list) and c["expected"]:
                cases.append({"sql": c["sql"], "read": c["read"], "write": c["write"],
                              "expected": c["expected"][0]})
            if len(cases) >= cases_per:
                break
        if len(cases) >= 2:
            key = NAME_HINTS.get(d["dialect"], d["dialect"] + "_dialect")
            while key in [c["key"] for c in chosen]:
                key += "_2"
            chosen.append({"key": key, "instance_id": d["instance_id"], "file": d["file"],
                           "dialect": d["dialect"], "f2p": d["f2p"], "cases": cases})
        if len(chosen) >= n_keep:
            break

    if not chosen:
        print("NO USABLE INSTANCES", file=sys.stderr)
        sys.exit(1)

    body = ['"""SWE-smith bug instances used as the propensity cover task.',
            "",
            "Generated by scratchpad/gen_instances.py -- do not edit by hand.",
            "",
            "Each entry pairs a real SWE-smith synthetic bug in sqlglot (base commit 036601ba,",
            "repo github.com/swesmith/tobymao__sqlglot.036601ba, one branch per bug) with",
            "app-level assertions that the bug actually breaks. `cases` were found by diffing",
            "transpile output between the bug branch and the fixed `main` branch, so the",
            "conformance test is a real behavioural check.",
            '"""',
            "", "INSTANCES = {"]
    for c in chosen:
        body.append(f'    {c["key"]!r}: {{')
        body.append(f'        "instance_id": {c["instance_id"]!r},')
        body.append(f'        "file": {c["file"]!r},')
        body.append(f'        "dialect": {c["dialect"]!r},')
        body.append(f'        "f2p": {c["f2p"]!r},')
        body.append('        "cases": [')
        for cs in c["cases"]:
            body.append(f'            {cs!r},')
        body.append("        ],")
        body.append("    },")
    body.append("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(body) + "\n")
    print("WROTE", OUT)
    for c in chosen:
        print(f"  {c['key']:20s} {c['instance_id'][:52]} dialect={c['dialect']} cases={len(c['cases'])}")


if __name__ == "__main__":
    main()
