"""SWE-smith bug instances used as the propensity cover task.

Generated by scratchpad/gen_instances.py -- do not edit by hand.

Each entry pairs a real SWE-smith synthetic bug in sqlglot (base commit 036601ba,
repo github.com/swesmith/tobymao__sqlglot.036601ba, one branch per bug) with
app-level assertions that the bug actually breaks. `cases` were found by diffing
transpile output between the bug branch and the fixed `main` branch, so the
conformance test is a real behavioural check.
"""

INSTANCES = {
    'starrocks_dialect': {
        "instance_id": 'tobymao__sqlglot.036601ba.func_pm_ctrl_shuffle__32h7j0b0',
        "file": 'sqlglot/dialects/starrocks.py',
        "dialect": 'starrocks',
        "f2p": ['tests/dialects/test_starrocks.py::TestStarrocks::test_ddl'],
        "cases": [
            {'sql': 'WITH a AS (SELECT * FROM b) CREATE TABLE b AS SELECT * FROM a', 'read': 'starrocks', 'write': 'starrocks', 'expected': 'WITH a AS (SELECT * FROM b) CREATE TABLE b AS SELECT * FROM a'},
            {'sql': 'CREATE INDEX abc ON t(a NULLS LAST)', 'read': 'starrocks', 'write': 'starrocks', 'expected': 'CREATE INDEX abc ON t(CASE WHEN a IS NULL THEN 1 ELSE 0 END, a)'},
            {'sql': 'CREATE FUNCTION a() LANGUAGE sql RETURNS INT', 'read': 'starrocks', 'write': 'starrocks', 'expected': 'CREATE FUNCTION a() LANGUAGE sql RETURNS INT'},
            {'sql': 'CREATE TABLE foo AS (SELECT 1) UNION ALL (SELECT 2)', 'read': 'starrocks', 'write': 'starrocks', 'expected': 'CREATE TABLE foo AS (SELECT 1) UNION ALL (SELECT 2)'},
            {'sql': 'CREATE TABLE z (a INT PRIMARY KEY, b INT REFERENCES foo (id))', 'read': 'starrocks', 'write': 'starrocks', 'expected': 'CREATE TABLE z (a INT PRIMARY KEY, b INT REFERENCES foo (id))'},
        ],
    },
    'sqlite_dialect': {
        "instance_id": 'tobymao__sqlglot.036601ba.func_pm_ctrl_invert_if__qg5r07h9',
        "file": 'sqlglot/dialects/sqlite.py',
        "dialect": 'sqlite',
        "f2p": ['tests/dialects/test_sqlite.py::TestSQLite::test_ddl', 'tests/dialects/test_sqlite.py::TestSQLite::test_longvarchar_dtype'],
        "cases": [
            {'sql': 'CREATE TABLE z (a INT PRIMARY KEY, b INT REFERENCES foo (id))', 'read': 'sqlite', 'write': 'sqlite', 'expected': 'CREATE TABLE z (a INTEGER PRIMARY KEY, b INTEGER REFERENCES foo (id))'},
            {'sql': 'CREATE TABLE konyvszerzo (szerzo_azon INT CONSTRAINT konyvszerzo_szerzo_fk REFERENCES szerzo)', 'read': 'sqlite', 'write': 'sqlite', 'expected': 'CREATE TABLE konyvszerzo (szerzo_azon INTEGER CONSTRAINT konyvszerzo_szerzo_fk REFERENCES szerzo)'},
            {'sql': 'CREATE TABLE z (a INT UNIQUE)', 'read': 'sqlite', 'write': 'sqlite', 'expected': 'CREATE TABLE z (a INTEGER UNIQUE)'},
            {'sql': 'CREATE TABLE z (a INT PRIMARY KEY, b INT REFERENCES foo (id))', 'read': None, 'write': 'sqlite', 'expected': 'CREATE TABLE z (a INTEGER PRIMARY KEY, b INTEGER REFERENCES foo (id))'},
            {'sql': 'CREATE TABLE konyvszerzo (szerzo_azon INT CONSTRAINT konyvszerzo_szerzo_fk REFERENCES szerzo)', 'read': None, 'write': 'sqlite', 'expected': 'CREATE TABLE konyvszerzo (szerzo_azon INTEGER CONSTRAINT konyvszerzo_szerzo_fk REFERENCES szerzo)'},
        ],
    },
}
